server:
  port: 8080

spring:
  application:
    name: MS-PRODUCTS
  datasource:
    url: jdbc:mysql://${DB_URL}/db-product
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  packages-to-scan: com.linktic.ms.products.infrastructure.rest.router

handle:
  exception:
    business: Business error occurred
    system: System error occurred

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}

aws:
  region: ${AWS_REGION}
  sqs:
    product-created-queue-url: ${AWS_QUEUE_CREATE_URL}
    delete-queue-url: ${AWS_QUEUE_DELETE_URL}
