name: Build MS Product Image

on:
  workflow_dispatch:

jobs:
  build-ms-product:
    runs-on: ubuntu-latest
    environment: env_prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Make gradlew executable for MS-Product
        run: chmod +x ./ms-products/gradlew

      - name: Build MS-Product without tests
        run: |
          cd ms-products
          ./gradlew build -x test

      - name: Build Docker Image for MS-Product
        run: |
          cd ms-products
          docker build --no-cache -t ingflorez940315/img_ms_product_2025_repo:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ingflorez940315/img_ms_product_2025_repo:latest