name: Build Eureka Image

on:
  workflow_dispatch:

jobs:
  build-eureka:
    runs-on: ubuntu-latest
    environment: env_prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Make gradlew executable for Eureka
        run: chmod +x ./ms-eureka/gradlew

      - name: Build Eureka Image
        run: |
          cd ms-eureka
          ./gradlew build -x test
          docker build --no-cache -t ingflorez940315/eureka_2025_repo:latest .
          docker push ingflorez940315/eureka_2025_repo:latest
